name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21  # Use the desired Java version here

      - name: Build with Maven
        run: mvn package
        working-directory: . # the dot is referring to the project root directory

      - name: Run Tests
        run: mvn test
        working-directory: src/test/java # the dot is referring to the project root directory

      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}


      - name: Deploy to DigitalOcean
        if: success()
        run: |
          scp -r target/cihubdemo.jar root@${{ secrets.DROPLET_IP }}:/root/mytestapp
        continue-on-error: true
