name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21  # Use the desired Java version here
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package


      - name: Run Tests
        run: mvn test


      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PATH }}


      - name: Deploy to DigitalOcean
        if: success()
        run: |
          scp -r target/cihubdemo.jar root@${{ secrets.DROPLET_IP }}:/root/mytestapp
        continue-on-error: true
